version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: Maggie13!
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - /home/docker/financestack/postgres:/var/lib/postgresql/data # Persist data

  agent:
    image: portainer/agent:latest # Use the latest Portainer agent image
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Connect to the Docker daemon
      - /var/lib/docker/volumes:/var/lib/docker/volumes # For Docker volumes management
    ports:
      - "9001:9001" # Portainer agent listens on port 9001
