version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: admindb
      POSTGRES_PASSWORD: Maggie13!
    ports:
      - "5432:5432" # Map container port 5432 to host port 5432
    volumes:
      - /home/docker/financestack/postgres:/var/lib/postgresql/data # Persist data